CREATE TABLE FORMULAR (
  REFERENZ_ID            NUMBER(19, 0) NOT NULL,
  TEXT                   VARCHAR2(1000 CHAR),
  THEMA                  VARCHAR2(255 CHAR),
  ABTEILUNG              VARCHAR2(255 CHAR),
  TEAM                   VARCHAR2(255 CHAR),
  SCHLAGWORTE            VARCHAR2(1000 CHAR),
  LINK                   VARCHAR2(255 CHAR),
  FORMAT                 VARCHAR2(255 CHAR),
  BESCHREIBUNG           VARCHAR2(255 CHAR),
  PRIMARY KEY (REFERENZ_ID)
);

